//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedZueva10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Подразделение.
    /// </summary>
    // *** Start programmer edit section *** (Подразделение CustomAttributes)

    // *** End programmer edit section *** (Подразделение CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПодразделениеE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ПодразделениеL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Подразделение : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Подразделение CustomMembers)

        // *** End programmer edit section *** (Подразделение CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Подразделение.Наименование CustomAttributes)

        // *** End programmer edit section *** (Подразделение.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Подразделение.Наименование Get start)

                // *** End programmer edit section *** (Подразделение.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Подразделение.Наименование Get end)

                // *** End programmer edit section *** (Подразделение.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Подразделение.Наименование Set start)

                // *** End programmer edit section *** (Подразделение.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Подразделение.Наименование Set end)

                // *** End programmer edit section *** (Подразделение.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПодразделениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПодразделениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПодразделениеE", typeof(IIS.UchetMedZueva10.Подразделение));
                }
            }
            
            /// <summary>
            /// "ПодразделениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПодразделениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПодразделениеL", typeof(IIS.UchetMedZueva10.Подразделение));
                }
            }
        }
    }
}
